// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface IFreeLatestVideosFields {
  /** Preview Image */
  previewImage: Asset;

  /** Tag Background Color */
  tagColor?: string | undefined;

  /** Tag Name */
  tagName: string;

  /** Tag Text Color */
  tagTextColor?: string | undefined;

  /** Champion Name */
  championName: string;

  /** Title */
  title: string;

  /** Time And Type Of Competition */
  timeAndTypeOfCompetition: string;

  /** Match Type */
  matchType: (
    | "Boxen"
    | "Doku"
    | "Karate"
    | "Kickboxen"
    | "MMA"
    | "Muay Thai"
    | "Royal FC"
  )[];
}

export interface IFreeLatestVideos extends Entry<IFreeLatestVideosFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "freeLatestVideos";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomePageFields {}

export interface IHomePage extends Entry<IHomePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "homePage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomePageAdvertisementFields {
  /** Advertisement URL */
  advertisementUrl: string;

  /** Advertisement Image */
  advertisementImage?: Asset | undefined;

  /** Image Alternation */
  imageAlternation: string;
}

export interface IHomePageAdvertisement
  extends Entry<IHomePageAdvertisementFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "homePageAdvertisement";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IRecommendedVideosFields {
  /** Preview Image */
  previewImage: Asset;

  /** Tag Background Color */
  tagColor?: string | undefined;

  /** Tag Name */
  tagName: string;

  /** Tag Text Color */
  tagTextColor?: string | undefined;

  /** Champion Name */
  championName: string;

  /** Title */
  title: string;

  /** Time And Type Of Competition */
  timeAndTypeOfCompetition: string;

  /** Match Type */
  matchType: (
    | "Boxen"
    | "Doku"
    | "Karate"
    | "Kickboxen"
    | "MMA"
    | "Muay Thai"
  )[];
}

export interface IRecommendedVideos extends Entry<IRecommendedVideosFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "recommendedVideos";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISliderBannerFields {
  /** Background Image */
  backgroundImage: Asset;

  /** title */
  title: string;

  /** date */
  date: string;

  /** Show Address */
  showAddress: string;

  /** Ticket Price */
  ticketPrice: number;

  /** Live URL */
  liveUrl: string;
}

export interface ISliderBanner extends Entry<ISliderBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sliderBanner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IUpComingFightsFields {
  /** fight image */
  fightImage?: Asset | undefined;

  /** title */
  title: string;

  /** match date */
  matchDate: string;

  /** ticket price */
  ticketPrice: number;
}

export interface IUpComingFights extends Entry<IUpComingFightsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "upComingFights";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "freeLatestVideos"
  | "homePage"
  | "homePageAdvertisement"
  | "recommendedVideos"
  | "sliderBanner"
  | "upComingFights";

export type IEntry =
  | IFreeLatestVideos
  | IHomePage
  | IHomePageAdvertisement
  | IRecommendedVideos
  | ISliderBanner
  | IUpComingFights;

export type LOCALE_CODE = "de" | "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
