// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface IAdvertisementsFields {
  /** Advertisement URL */
  advertisementUrl: string;

  /** Advertisement Image */
  advertisementImage?: Asset | undefined;

  /** Image Alternation */
  imageAlternation: string;

  /** Advertisement Description */
  advertisementDescription: string;
}

export interface IAdvertisements extends Entry<IAdvertisementsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "advertisements";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFreeLatestVideosFields {
  /** Preview Image */
  previewImage: Asset;

  /** Tag Background Color */
  tagColor?: string | undefined;

  /** Tag Name */
  tagName: string;

  /** Tag Text Color */
  tagTextColor?: string | undefined;

  /** Champion Name */
  championName: string;

  /** Title */
  title: string;

  /** Time And Type Of Competition */
  timeAndTypeOfCompetition: string;

  /** Event Type */
  matchType: (
    | "Armdrücken"
    | "BJJ"
    | "Boxen"
    | "Doku"
    | "Karate"
    | "Kickboxen"
    | "MMA"
    | "Muay Thai"
    | "Pro Wrestling"
    | "Ringen"
    | "Show"
    | "Talk"
  )[];

  /** Event Date */
  eventDate?: string | undefined;

  /** price */
  price: number;
}

export interface IFreeLatestVideos extends Entry<IFreeLatestVideosFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "freeLatestVideos";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomePageFields {}

export interface IHomePage extends Entry<IHomePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "homePage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILiveFields {
  /** fight image */
  fightImage?: Asset | undefined;

  /** title */
  title: string;

  /** match date */
  matchDate: string;

  /** ticket price */
  ticketPrice: number;

  /** Match Type */
  matchType:
    | "Am Beliebtesten"
    | "TV"
    | "Zuletzt Hinzugefügt"
    | "Top Heis"
    | "Boxen"
    | "MMA"
    | "Royal FC"
    | "Auch Beliebt"
    | "Pro Wrestling";
}

export interface ILive extends Entry<ILiveFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "live";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface INewsFields {
  /** title */
  title: string;

  /** date */
  date: string;

  /** sub title */
  subTitle?: string | undefined;

  /** description */
  description: string;

  /** image */
  image: Asset;
}

export interface INews extends Entry<INewsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "news";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageveranstaltungenFields {
  /** Section Dates */
  sectionDates?: Record<string, any> | undefined;
}

export interface IPageveranstaltungen
  extends Entry<IPageveranstaltungenFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "pageveranstaltungen";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IQencodeTranscodedAssetFields {
  /** Title */
  title?: string | undefined;

  /** Transcoding Data */
  task_data?: Record<string, any> | undefined;

  /** Media */
  media?: Asset | undefined;
}

export interface IQencodeTranscodedAsset
  extends Entry<IQencodeTranscodedAssetFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "qencodeTranscodedAsset";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IRecommendedVideosFields {
  /** Preview Image */
  previewImage: Asset;

  /** Tag Background Color */
  tagColor?: string | undefined;

  /** Tag Name */
  tagName: string;

  /** Tag Text Color */
  tagTextColor?: string | undefined;

  /** Champion Name */
  championName: string;

  /** Title */
  title: string;

  /** Time And Type Of Competition */
  timeAndTypeOfCompetition: string;

  /** Match Type */
  matchType: (
    | "Boxen"
    | "Doku"
    | "Karate"
    | "Kickboxen"
    | "MMA"
    | "Muay Thai"
  )[];
}

export interface IRecommendedVideos extends Entry<IRecommendedVideosFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "recommendedVideos";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISliderBannerFields {
  /** Background Image */
  backgroundImage: Asset;

  /** title */
  title: string;

  /** date */
  date: string;

  /** Show Address */
  showAddress: string;

  /** Ticket Price */
  ticketPrice: number;

  /** Live URL */
  liveUrl: string;
}

export interface ISliderBanner extends Entry<ISliderBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sliderBanner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITicketsFields {
  /** Ticket Cover */
  ticketCover: Asset;

  /** Event Title */
  eventTitle: string;

  /** Event Time */
  eventTime: string;

  /** Price */
  price: number;

  /** Entering Time */
  enteringTime: number;

  /** Beginning Time */
  beginningTime: string;

  /** Event Duration */
  eventDuration: number;

  /** location */
  location: { lat: number; lon: number };
}

export interface ITickets extends Entry<ITicketsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tickets";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IUpComingFightsFields {
  /** fight image */
  fightImage?: Asset | undefined;

  /** title */
  title: string;

  /** match date */
  matchDate: string;

  /** ticket price */
  ticketPrice: number;
}

export interface IUpComingFights extends Entry<IUpComingFightsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "upComingFights";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "advertisements"
  | "freeLatestVideos"
  | "homePage"
  | "live"
  | "news"
  | "pageveranstaltungen"
  | "qencodeTranscodedAsset"
  | "recommendedVideos"
  | "sliderBanner"
  | "tickets"
  | "upComingFights";

export type IEntry =
  | IAdvertisements
  | IFreeLatestVideos
  | IHomePage
  | ILive
  | INews
  | IPageveranstaltungen
  | IQencodeTranscodedAsset
  | IRecommendedVideos
  | ISliderBanner
  | ITickets
  | IUpComingFights;

export type LOCALE_CODE = "de" | "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
