// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface ITestArticleFields {
  /** title */
  title?: string | undefined;

  /** description */
  description?: Document | undefined;

  /** publish date */
  publishDate?: string | undefined;
}

export interface ITestArticle extends Entry<ITestArticleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "testArticle";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "testArticle";

export type IEntry = ITestArticle;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
