import React from "react";
import "./theme/globals.css";
import localFont from "next/font/local";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import { Login } from "./components/Login/Login";
import { PaymentMethod } from "./components/PaymentMethod/Payment";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

const amisProFont = localFont({
  src: [
    {
      path: "./assets/fonts/amsi-pro/AmsiProNarw-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/amsi-pro/AmsiPro-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./assets/fonts/amsi-pro/AmsiPro-Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-amis-pro",
});

export const metadata = {
  title: "Fight24",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: string };
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={`${amisProFont.variable} font-sans bg-base-black`}>
        <Header lng={lng} />
        <main className="main">
          {/* <PaymentMethod /> */}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
